name: Build Android

on: workflow_dispatch

jobs:
  build-android:
    name: Build Android
    runs-on: ubuntu-latest
    environment: develop
    defaults:
      run:
        working-directory: android

    env:
      JAVA_OPTS: "-Xms512m -Xmx2g"
      GRADLE_OPTS: '-Xmx3g -Dorg.gradle.daemon=false -Dorg.gradle.jvmargs="-Xmx2g -XX:+HeapDumpOnOutOfMemoryError"'
      TERM: dumb

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Decode Keystore and google-services.json
        run: |
          echo ${{ secrets.KEYSTORE_BASE_64 }} | base64 -d > ./app/key.keystore
          echo ${{ secrets.GOOGLE_SERVICES_JSON_BASE_64 }} | base64 -d > ./app/google-services.json          

      - uses: c-hive/gha-yarn-cache@v2

      - name: Install dependencies
        run: yarn install --prefer-offline

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 11.0.14
          cache: "gradle"

      - name: Make Gradlew Executable
        run: chmod +x ./gradlew

      - name: Set gradle.properties
        run: |
          echo -e "" > ./gradle.properties
          echo -e android.useAndroidX=true >> ./gradle.properties
          echo -e android.enableJetifier=true >> ./gradle.properties
          echo -e FLIPPER_VERSION=0.51.0 >> ./gradle.properties
          echo -e VERSIONCODE=${{ github.run_number }} >> ./gradle.properties
          echo -e APPLICATION_ID=${{ secrets.ANDROID_APPLICATION_ID }} >> ./gradle.properties
          echo -e BugsnagAPIKey="" >> ./gradle.properties
          echo -e KEYSTORE=./app/key.keystore >> ./gradle.properties
          echo -e KEYSTORE_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> ./gradle.properties
          echo -e KEY_ALIAS=${{ secrets.KEY_ALIAS }} >> ./gradle.properties
          echo -e KEY_PASSWORD=${{ secrets.KEYSTORE_PASSWORD }} >> ./gradle.properties

      - name: Generate App APK
        run: |
          ./gradlew bundleExperimentalFossRelease --no-daemon

      - name: Store Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: app.bundle-${{ github.event.number }}
          path: app/build/generated/assets/react/experimentalFoss/release/app.bundle
